branches:
  only:
    - master
    - development

language: android
dist: trusty
jdk: oraclejdk8

env:
  global:
    - ANDROID_API=29
    - EMULATOR_API=21
    - ANDROID_BUILD_TOOLS=29.0.0
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=5 # minutes
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API
    - extra-android-m2repository
    - sys-img-$ANDROID_ABI-google_apis-$EMULATOR_API

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - cd Cars
  - "./gradlew clean check"

